<!--
Auto-generated by: https://github.com/threlte/threlte/tree/main/packages/gltf
Command: npx @threlte/gltf@1.0.1 blankBox.glb
-->

<script>
	import { Group } from 'three';
	import { T, forwardEventHandlers } from '@threlte/core';
	import { useGltf, useGltfAnimations } from '@threlte/extras';

	export const ref = new Group();

	const gltf = useGltf('/blankBox.glb');
	export const { actions, mixer } = useGltfAnimations(gltf, ref);

	const component = forwardEventHandlers();
</script>

<T is={ref} dispose={true} {...$$restProps} bind:this={$component}>
	{#await gltf}
		<slot name="fallback" />
	{:then gltf}
		<T.Group name="tutorial">
			<T.Group name="boxArm">
				<T is={gltf.nodes.Bone} />
				<T.SkinnedMesh
					name="Box"
					geometry={gltf.nodes.Box.geometry}
					material={gltf.nodes.Box.material}
					skeleton={gltf.nodes.Box.skeleton}
				/>
			</T.Group>
		</T.Group>
	{:catch error}
		<slot name="error" {error} />
	{/await}

	<slot {ref} />
</T>
