<!--
Auto-generated by: https://github.com/threlte/threlte/tree/main/packages/gltf
Command: npx @threlte/gltf@1.0.1 miniPack.glb
-->

<script>
	import { Group } from 'three';
	import { T, forwardEventHandlers } from '@threlte/core';
	import { useGltf, useGltfAnimations } from '@threlte/extras';

	// custom code

	import { actionsStore } from './stores/packManage';

	export const ref = new Group();

	const gltf = useGltf('/miniPack.glb');
	export const { actions, mixer } = useGltfAnimations(gltf, ref);

	// $: console.log($actions.ArmatureAction);
	$: console.log(mixer);
	// $: $actions['ArmatureAction']?.play();
	// useGltfAnimations(gltf);

	$: if ($actionsStore == 'Play') {
		mixer.timeScale = 1;
		$actions['ArmatureAction']?.play();
	} else mixer.timeScale = 0.01;

	const component = forwardEventHandlers();
</script>

<T is={ref} dispose={false} {...$$restProps} bind:this={$component}>
	{#await gltf}
		<slot name="fallback" />
	{:then gltf}
		<T.Group name="Scene">
			<T.Group name="Armature" position={[-0.49, -0.8, -0.11]} rotation={[0.15, -0.36, 0.05]}>
				<T is={gltf.nodes.Bone} />
				<T.SkinnedMesh
					name="Plane"
					geometry={gltf.nodes.Plane.geometry}
					material={gltf.materials['Material.001']}
					skeleton={gltf.nodes.Plane.skeleton}
				/>
			</T.Group>
		</T.Group>
	{:catch error}
		<slot name="error" {error} />
	{/await}

	<slot {ref} />
</T>
