<!--
Auto-generated by: https://github.com/threlte/threlte/tree/main/packages/gltf
Command: npx @threlte/gltf@1.0.1 .\3pack_B.glb
-->

<script>
	import { onMount } from 'svelte';
	import { Group } from 'three';
	import { T, forwardEventHandlers } from '@threlte/core';
	import { useGltf, useGltfAnimations } from '@threlte/extras';
	import { Pane } from 'tweakpane';

	export const ref = new Group();

	const gltf = useGltf('/3pack_B.glb');
	// $: console.log($gltf);

	export const { actions, mixer } = useGltfAnimations(gltf, ref);

	$: console.log($actions['packAnimation']);
	const component = forwardEventHandlers();

	// frames calculate
	let totalFrames = 0; // default value
	// Calculate total frames using duration of the animation (assuming 30 FPS).
	$: if ($actions && $actions['packAnimation']) {
		const durationInSeconds = $actions['packAnimation'].getClip().duration;
		totalFrames = Math.round(durationInSeconds * 24);
		console.log(totalFrames);
	}

	let params = {
		playAnimation: false, // Start with animation paused
		speed: 0.5, // Animation speed
		frame: 0 // animation frame
	};

	const pane = new Pane();

	// Speed control
	pane.addBinding(params, 'speed').on('change', (value) => {
		if (mixer) {
			mixer.timeScale = value.value; // Adjust the animation playback speed
			// console.log(mixer);
		}
	});

	// Play/pause control
	pane.addBinding(params, 'playAnimation', { label: 'Play Animation' }).on('change', (value) => {
		// console.log(value);
		if (value.value) {
			$actions['packAnimation'].paused = false;
			$actions['packAnimation']?.play();
			console.log('play');
		} else {
			$actions['packAnimation'].paused = true;
			console.log('pause');
		}
	});

	// frame control
	pane
		.addBinding(params, 'frame', {
			label: 'Animation Frame',
			step: 1,
			min: 0,
			max: 42
		})
		.on('change', (value) => {
			const timeInSeconds = value.value / 24;
			$actions['packAnimation'].time = timeInSeconds;

			console.log(timeInSeconds);
		});
</script>

<T is={ref} dispose={false} {...$$restProps} bind:this={$component}>
	{#await gltf}
		<slot name="fallback" />
	{:then gltf}
		<T.Group name="Scene">
			<T.Group name="packArm" position={[-1.26, 0, 0]} rotation={[Math.PI / 2, 0, 0]}>
				<T is={gltf.nodes.Bone} />
				<T.SkinnedMesh
					name="pack"
					geometry={gltf.nodes.pack.geometry}
					material={gltf.materials['Material.008']}
					skeleton={gltf.nodes.pack.skeleton}
				/>
			</T.Group>
		</T.Group>
	{:catch error}
		<slot name="error" {error} />
	{/await}

	<slot {ref} />
</T>
